### ISSUE TITLE
How are you getting past login?

### ISSUE THREAD

**Issue by PeteDuncanson** [bergmania/umbraco-cypress-testhelpers#11]
Love that there is a HQ endorsed way to do automated testing now. Query how do we get logged into the back end? Roll our own or is there something around that we can use?

I've got this sorted in my old go at this https://github.com/PeteDuncanson/Umbraco-UI-Tests which I can port over to Cypress and give you a PR but if its already solved I'd rather use that :)

**Comment by bergmania** [comment]
Hi @PeteDuncanson 

You can take inspiration in one of the cypress tests added to the project
E.g. https://github.com/bergmania/umbraco-cypress-testhelpers/blob/dev/cypress/integration/Settings/dataTypes.js

Here you can see it login before each test, using the values `username` and `password` specified in the [cypress.json](https://github.com/bergmania/umbraco-cypress-testhelpers/blob/dev/cypress.json).

Currently there is a bug, so the login cannot handle if the tours popup. So these needs to be disabled on the user signing in.

**Comment by PeteDuncanson** [comment]
Thank you.

Found this https://github.com/bergmania/umbraco-cypress-testhelpers/blob/dev/src/cypress/commands/umbracoLogin.js

Interesting that you appear to be just firing in the form post directly and not going through the UI. I want to test the UI so I'll roll my own for now and if any good feed it back.

**Comment by bergmania** [comment]
Yes, we should only use UI when we want to test the U, and not if we try to set up the state.
https://docs.cypress.io/guides/getting-started/testing-your-app.html#Bypassing-your-UI
