### ISSUE TITLE
Road map?

### ISSUE THREAD

**Issue by PeteDuncanson** [bergmania/umbraco-cypress-testhelpers#13]
Hi

Been seeing the PR's and commits for this one come in the last few weeks/months (great work Thomas). Just wondering, what is the plan/direction for the work that is on going on this at the mo?

I'm wanting to use this myself on a project I'm working on and might want to push some stuff in too but not sure what is being worked on and what isn't. Where is it heading or are you just adding stuff as you find it?

Pete

**Comment by bergmania** [comment]
Hi @PeteDuncanson.

There is no official road map. The plan so far is split in two:

1. This package
1. The actual tests of different products (Umbraco CMS, Umbraco Forms, etc...)

For this package the plan is to add stuff as we need it for actual tests.

For the different products, I only know about Umbraco CMS.
Here it is our plan to create a new project with cypress tests, which has to be executed manually in the first phase. 
This project will use this package for custom commands.
We plan to create the project in the Umbraco solution in the sprint that started today (so within 14 days).
The tests from this project, that is relevant for the CMS without forms, will be moved to the new project.
